import { test, expect } from '../fixtures/pages';

test.describe('Tasks', { tag: ['@e2e'] }, () => {
  test('adds a task, toggles completion, filters, and deletes', async ({ tasksPage }) => {
    await tasksPage.goto();
    await expect(tasksPage.heading).toBeVisible();

    const title = `E2E task ${Date.now()}`;
    await tasksPage.openAddTaskDialog();
    await tasksPage.taskTitleInput.fill(title);
    await tasksPage.taskDescriptionInput.fill('Generated by Playwright');
    await tasksPage.setTaskPriority('High');
    await tasksPage.submitTaskButton.click();
    await expect(tasksPage.addTaskDialog).toBeHidden();

    await expect(tasksPage.taskList.getByText(title, { exact: false })).toBeVisible();

    const row = tasksPage.taskList.getByTestId(/^task-item-/).filter({ hasText: title });
    const checkbox = row.getByRole('checkbox');
    await checkbox.click();
    await expect(checkbox).toBeChecked();

    await tasksPage.setFilter('Completed');
    await expect(tasksPage.taskList).toContainText(title);

    await tasksPage.setFilter('Pending');
    await expect(tasksPage.taskList).not.toContainText(title);

    await tasksPage.setFilter('All Tasks');
    const rowAgain = tasksPage.taskList.getByTestId(/^task-item-/).filter({ hasText: title });
    await rowAgain.getByRole('button').click();
    await expect(tasksPage.taskList).not.toContainText(title);
  });
});
